Repository Team-DragMe/DragMe-Server, pull requests merged in 2022-07, with the labels that each got.

#4 [FEAT] Eslint, Prettier 설정
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  package.json
  src/index.ts
  src/modules/statusCode.ts
  src/services/index.ts
  yarn.lock
Labels: enhancement, ❤️‍🔥 hyositive

#7 [FEAT] User 콜렉션 생성
  .vscode/settings.json
  package.json
  src/interfaces/user/UserInfo.ts
  src/loaders/db.ts
  src/models/User.ts
  yarn.lock
Labels: enhancement, ❤️‍🔥 hyositive

#8 [FEAT] Information 콜렉션 생성
  src/interfaces/information/InformationInfo.ts
  src/loaders/db.ts
  src/models/Information.ts
Labels: enhancement, 💀 m1njae

#11 [FEAT] Schedule 콜렉션 생성
  src/interfaces/schedule/ScheduleInfo.ts
  src/loaders/db.ts
  src/models/Schedule.ts
Labels: enhancement, ❤️‍🔥 hyositive

#13 [FIX] User, Information 컬렉션에 timestamps 추가
  src/models/Information.ts
  src/models/User.ts
Labels: bug, ❤️‍🔥 hyositive

#17 [FEAT] 계획블록 생성 API
  src/controllers/ScheduleController.ts
  src/controllers/index.ts
  src/interfaces/schedule/ScheduleCreateDto.ts
  src/interfaces/schedule/ScheduleInfo.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/routes/index.ts
  src/services/ScheduleService.ts
  src/services/index.ts
Labels: enhancement, ❤️‍🔥 hyositive

#21 [FEAT] 계획블록 미루기 API
  src/controllers/InformationController.ts
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#25 [FEAT] 일간계획 정보 조회 API
  src/controllers/InformationController.ts
  src/interfaces/information/InformationResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/InformationRouter.ts
  src/services/InformationService.ts
Labels: enhancement, 💀 m1njae

#29 [FIX] 계획블록 미룰 시 시간 데이터 삭제
  src/controllers/ScheduleController.ts
  src/services/InformationService.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#30 [FEAT] 감정 이모티콘 설정 API
  src/controllers/InformationController.ts
  src/interfaces/information/InformationCreateDto.ts
  src/modules/responseMessage.ts
  src/routes/InformationRouter.ts
  src/services/InformationService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#33 [FEAT] 미뤄진 계획블록 목록 조회 API
  src/controllers/ScheduleController.ts
  src/interfaces/schedule/RescheduleListGetDto.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#35 [FEAT] 자주 사용하는 계획 등록 API
  src/controllers/ScheduleController.ts
  src/interfaces/schedule/ScheduleCreateDto.ts
  src/models/Schedule.ts
  src/modules/calculateOrderIndex.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#37 [FEAT] 자주 사용하는 계획 조회 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#41 [FIX] 자주 사용하는 계획 등록, 계획블록 미루기 시 subSchedules 내 데이터 처리
  src/controllers/ScheduleController.ts
  src/interfaces/schedule/ScheduleCreateDto.ts
  src/models/Schedule.ts
  src/services/ScheduleService.ts
Labels: bug, ❤️‍🔥 hyositive

#43 [FEAT] 미룬 계획블록 계획표로 옮기기 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#45 [FEAT] 자주 사용하는 계획블록 계획표로 옮기기 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#48 [FEAT] 계획블록 완료하기 API
  src/controllers/ScheduleController.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#49 [FEAT] 계획블록 순서 변경 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#52 [FIX] 계획블록 이름 수정 API ScheduleId request로 받도록 수정
  src/controllers/ScheduleController.ts
Labels: bug, ❤️‍🔥 hyositive

#54 [FEAT] 계획블록 카테고리 변경 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#56 [FEAT] 계획블록 시간 설정 API
  src/controllers/ScheduleController.ts
  src/interfaces/schedule/TimeDto.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#58 [FEAT] 계획블록 시간 삭제 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#59 [FEAT] 정보 작성 API
  src/controllers/InformationController.ts
  src/interfaces/information/InformationCreateDto.ts
  src/modules/responseMessage.ts
  src/routes/InformationRouter.ts
  src/services/InformationService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#62 [FEAT] 날짜별 일정 존재 여부 조회 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#64 [FEAT] 계획블록 삭제 API
  src/controllers/ScheduleController.ts
  src/interfaces/information/InformationCreateDto.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#67 [FEAT] Cors 설정
  package.json
  src/config/index.ts
  src/index.ts
  yarn.lock
Labels: enhancement, ❤️‍🔥 hyositive

#66 [FEAT] 하위 계획블록 조회 API
  src/controllers/ScheduleController.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#73 [FEAT] 계획블록 수정 API
  package.json
  src/controllers/ScheduleController.ts
  src/interfaces/schedule/SubScheduleIdTitleListDto.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
  yarn.lock
Labels: enhancement, ❤️‍🔥 hyositive

#71 [FIX] 계획블록 삭제하기 API 수정
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#78 [FEAT] 주간 계획 계획블록 리스트 조회 API
  src/controllers/ScheduleController.ts
  src/modules/calculateDaysOfWeek.ts
  src/modules/responseMessage.ts
  src/routes/ScheduleRouter.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#77 [FEAT] 월간 목표 조회 API
  src/controllers/InformationController.ts
  src/interfaces/information/DailyInformationResponseDto.ts
  src/interfaces/information/InformationResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/InformationRouter.ts
  src/services/InformationService.ts
Labels: enhancement, 💀 m1njae

#83 [IMPROVE] 일간 계획블록 리스트 조회 API 점검 및 보완
  .github/ISSUE_TEMPLATE/api_check.md
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#85 [IMPROVE] 정보 작성 API 점검 및 보완
  src/controllers/InformationController.ts
  src/controllers/ScheduleController.ts
  src/services/InformationService.ts
Labels: bug, enhancement, ❤️‍🔥 hyositive

#89 [FEAT] 주간 목표 조회 API
  src/controllers/InformationController.ts
  src/modules/responseMessage.ts
  src/routes/InformationRouter.ts
  src/services/InformationService.ts
Labels: enhancement, 💀 m1njae

#90 [IMPROVE] 계획블록 생성 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/interfaces/schedule/ScheduleCreateDto.ts
Labels: enhancement, ❤️‍🔥 hyositive

#92 [HOTFIX] userId 타입 일괄적으로 string으로 변경
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: bug, ❤️‍🔥 hyositive

#94 [IMPROVE] 미뤄진 계획블록 목록 조회 API 점검 및 보완
  src/controllers/ScheduleController.ts
Labels: enhancement, 💀 m1njae

#96 [IMPROVE] 일간 계획 정보 조회 API 수정 및 보완
  src/controllers/InformationController.ts
Labels: enhancement, 💀 m1njae

#100 [FIX] Cors allowedOrigins에 도메인 주소 추가
  src/index.ts
Labels: bug, ❤️‍🔥 hyositive

#103 [IMPROVE] 계획블록 수정 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#105 [IMPROVE] 자주 사용하는 계획 조회 API 점검 및 보완
  src/controllers/ScheduleController.ts
Labels: enhancement, ❤️‍🔥 hyositive

#107 [IMPROVE] 자주 사용하는 계획 등록 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#109 [IMPROVE] 계획블록 완료하기 API 수정 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#111 [IMPROVE] 계획블록 이름 수정 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#114 [IMPROVE] 하위 계획블록 조회 API 점검 및 수정
  src/controllers/ScheduleController.ts
Labels: enhancement, 💀 m1njae

#117 [IMPROVE] 날짜별 일정 존재 여부 조회 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#119 [IMPROVE] 자주 사용하는 계획블록 계획표로 옮기기 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#123 [IMPROVE] 계획블록 시간 설정 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#125 [IMPROVE] 계획블록 카테고리 변경 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, ❤️‍🔥 hyositive

#131 [FIX] 하위 계획블록 생성 시 date값 삭제
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: bug, ❤️‍🔥 hyositive

#133 [IMPROVE] 월간 목표 조회 API 점검 및 보완
  src/controllers/InformationController.ts
Labels: enhancement, 💀 m1njae

#135 [IMPROVE] 주간 목표 조회 API 점검 및 보완
  src/controllers/InformationController.ts
Labels: enhancement, 💀 m1njae

#137 [IMPROVE] 계획블록 요일 이동 API 점검 및 보완
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#139 [FIX] 주간 목표 조회하기 배열 수정
  src/services/InformationService.ts
Labels: bug, 💀 m1njae

#141 [FIX] 월간 조회 API 수정
  src/interfaces/information/DailyInformationResponseDto.ts
  src/interfaces/information/InformationResponseDto.ts
  src/services/InformationService.ts
Labels: bug, 💀 m1njae

#142 [FEAT] 테스트 환경 구축 및 husky를 통한 테스트 자동화, Schedule 테스트 코드 작성
  .husky/pre-commit
  babel.config.json
  jest.config.js
  nodemon.json
  package.json
  src/controllers/ScheduleController.ts
  src/index.ts
  src/modules/responseMessage.ts
  src/server.ts
  src/services/ScheduleService.ts
  test/schedule.spec.js
  yarn.lock
Labels: enhancement, ❤️‍🔥 hyositive

#144 [FIX] 계획블록 시간 삭제 API 수정
  .husky/pre-commit
  src/interfaces/schedule/TimeDto.ts
  src/services/ScheduleService.ts
Labels: bug, 💀 m1njae

#147 [FIX] 계획블록 완료하기 로직 수정
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: enhancement, 💀 m1njae

#149 [FIX] 계획블록 시간 설정 API 수정
  src/services/ScheduleService.ts
Labels: bug, 💀 m1njae

#151 [FIX] 계획블록 시간 삭제 Http Method PATCH로 변경
  src/routes/ScheduleRouter.ts
Labels: bug, 💀 m1njae

#153 [FIX] 미룰 계획블록, 자주 사용하는 계획블록 API 수정
  .husky/pre-commit
  src/services/ScheduleService.ts
Labels: bug, 💀 m1njae

#155 [FIX] 하위 계획블록 생성 시, 임시로 date를 하위 계획블록 flag로 사용하도록 수정
  src/services/ScheduleService.ts
Labels: bug, ❤️‍🔥 hyositive

#158 [FIX] 미룬 계획블록 - 일간 계획블록 이동 시 순서 설정 로직 수정
  src/controllers/ScheduleController.ts
  src/services/ScheduleService.ts
Labels: bug, ❤️‍🔥 hyositive

#163 [FIX] 하위 계획블록 flag 설정
  src/services/ScheduleService.ts
Labels: bug, 💀 m1njae

#166 [FIX] 일간 정보 조회 API response send 시 return 추가
  src/controllers/InformationController.ts
  test/information.spec.js
  test/schedule.spec.js
Labels: bug, ❤️‍🔥 hyositive
